plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.21'
	id 'maven-publish'
}
version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }
repositories { mavenCentral() }
dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	compileOnly "xyz.jpenilla:squaremap-api:${project.squaremap_version}"
	testImplementation "xyz.jpenilla:squaremap-api:${project.squaremap_version}"
	include(implementation('me.lucko:fabric-permissions-api:0.7.0'))
	testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') { expand 'version': project.version }
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }
java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
test { useJUnitPlatform() }
jar {
	from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } }
}
publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}
